name: Mirror to Gitee Repo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: Push Mirror
        run: |
          git clone  https://gitee.com/BruceIT/hutool-js.git 
          cd hutool-js
          git remote set-url --push origin git@github.com:BruceIT/hutool-js.git
          git fetch -p origin
          git push

